monitor = HDMI-A-1,1920x1080@60,0x0,1,transform,3
monitor = DP-1,2560x1440@120,1080x0,1
monitor = DP-2,2560x1440@120,3640x0,1

workspace = 1, monitor:HDMI-A-1, default:true
workspace = 2, monitor:HDMI-A-1
workspace = 3, monitor:HDMI-A-1
workspace = 4, monitor:DP-1, default:true
workspace = 5, monitor:DP-1
workspace = 6, monitor:DP-1
workspace = 7, monitor:DP-2, default:true
workspace = 8, monitor:DP-2
workspace = 9, monitor:DP-2

env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = XCURSOR_SIZE,24

exec-once = sleep 2 && discord --enable-features=UseOzonePlatform --ozone-platform=wayland
exec-once = bash -lc 'for i in {1..60}; do hyprctl clients | grep -qi "class: discord" && break; sleep 1; done; ghostty --title=btop-monitor -e btop'
