monitor = Virtual-1,2560x1440@60,0x0,1
monitor = Unknown-1,disable
monitor = ,disable

env = WLR_NO_HARDWARE_CURSORS,1
env = WLR_RENDERER_ALLOW_SOFTWARE,1
env = LIBVA_DRIVER_NAME,vmwgfx

decoration {
    blur {
        enabled = false
    }

    shadow {
        enabled = false
    }
}

animations {
    enabled = true
    bezier = quick, 0.15, 0, 0.1, 1
    animation = global, 1, 2, quick
    animation = workspaces, 1, 1.5, quick, slide
}

misc {
    vfr = true
    disable_autoreload = true
}
